# Generated by Django 5.2.7 on 2025-10-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
