# Generated by Django 5.2.7 on 2025-11-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
